name: Build csp-kit
on:
  push:
    branches: ['main']

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  cd:
    name: Build, test and publish csp-kit
    runs-on: ubuntu-latest
    permissions: write-all # This is needed to create a new git tag

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
        working-directory: ./src

      - run: npm run build
        working-directory: ./src

      - run: npm run test
        working-directory: ./src

      - name: Extract version from package.json
        id: extract_version
        run: echo ::set-output name=VERSION::$(node -p "require('./package.json').version")
        working-directory: ./src

      - name: Check if package.json version is listed in npm registry
        id: check_npm_version
        run: |
          VERSION=${{ steps.extract_version.outputs.VERSION }}
          if npm view csp-kit@$VERSION > /dev/null; then
            echo "Version $VERSION exists in npm registry"
            exit 1
          fi
        working-directory: ./src

      - name: Create Release
        id: create_release
        run: |
          gh release create v${{ steps.extract_version.outputs.VERSION }} --title "v${{ steps.extract_version.outputs.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run deploy
        name: Deploy to NPM
        working-directory: ./src
